### PR TITLE
Adds touchscreen scrolling for firefox 

### PR DESCRIPTION
**Pull request by lucaszanella**

### CODE REVIEW

**Comment by rolandguelle** [comment]
Are you running X or Wayland? Have you tried Wayland without the setting?

**Comment by lucaszanella** [comment]
I'm using Wayland, it's the default on Ubuntu 17.10. You have any suggestions?

also, when I touch the screen, the on screen keyboard shows up. The onboard app isn't even installed. I installed to see if I could disable this setting but it was already disabled and the keyboard keeps showing. You had a this problem? Know a solution?

**Comment by rolandguelle** [comment]
the keyboard is caribou, there are workarounds:
https://extensions.gnome.org/extension/1326/block-caribou/

But maybe there is another workaround like removing caribou from autostart, something like:
/etc/xdg/autostart/caribou-autostart.desktop
NoDisplay=false

**Comment by rolandguelle** [comment]
/etc/xdg/autostart/caribou-autostart.desktop
wont help, but down installing the extension:
download: https://github.com/keringar/cariboublocker and mv
mkdir -p ~/.local/share/gnome-shell/extensions/cariboublocker@git.keringar.xyz
logout, login helps

**Comment by lucaszanella** [comment]
you mean I need to put contents of this git inside  ~/.local/share/gnome-shell/extensions/cariboublocker? I did it and it wouldn't do anything

**Comment by lucaszanella** [comment]
I removed caribou package and autostart. Now the keyboard that opens is another: one very tiny in the corner. You have any idea how to remove this one?

**Comment by rolandguelle** [comment]
The gnome extension directory needs the same directory like the uuid in the extension metadata.json.
Could you try:
https://github.com/rolandguelle/razer-blade-stealth-linux/blob/master/README.md#touchscreen--keyboard-block-caribou

It works for me.
Maybe $ gsettings set org.gnome.shell enabled-extensions "['cariboublocker@git.keringar.xyz']" is not needed and after logout/login the extension could be enabled with the tweaks utility.

**Comment by lucaszanella** [comment]
thanks, it worked

**Pull request merged**
